// <auto-generated />
using System;
using EF_CodeFirst_Sample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CodeFirst_Sample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_CodeFirst_Sample.Models.Khoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Khoas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenKhoa = "CNTT"
                        },
                        new
                        {
                            Id = 2,
                            TenKhoa = "DT"
                        },
                        new
                        {
                            Id = 3,
                            TenKhoa = "SPCN"
                        });
                });

            modelBuilder.Entity("EF_CodeFirst_Sample.Models.Lop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhoaId")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("Lops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KhoaId = 1,
                            TenLop = "21T1"
                        },
                        new
                        {
                            Id = 2,
                            KhoaId = 1,
                            TenLop = "21T2"
                        },
                        new
                        {
                            Id = 3,
                            KhoaId = 1,
                            TenLop = "21T3"
                        });
                });

            modelBuilder.Entity("EF_CodeFirst_Sample.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LopId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LopId");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoTen = "NTruong Dinh Nhat",
                            LopId = 1,
                            NgaySinh = new DateTime(2003, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            HoTen = "Nguyen Duy Tung",
                            LopId = 2,
                            NgaySinh = new DateTime(2005, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            HoTen = "To Ngoc Hai",
                            LopId = 3,
                            NgaySinh = new DateTime(2004, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EF_CodeFirst_Sample.Models.Lop", b =>
                {
                    b.HasOne("EF_CodeFirst_Sample.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("EF_CodeFirst_Sample.Models.SinhVien", b =>
                {
                    b.HasOne("EF_CodeFirst_Sample.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");
                });
#pragma warning restore 612, 618
        }
    }
}
